repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: detect-private-key
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        entry: make lint
        types_or: ["javascript", "vue", "jsx", "ts", "tsx"]
